version: '3.8'

services:
  user-order-service:
    build:
      context: ./user-order-service
      dockerfile: Dockerfile
    container_name: cloudstore-user-order-service
    ports:
      - "8082:8082"
    networks:
      - cloudstore-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: cloudstore-product-service
    ports:
      - "8081:8081"
    networks:
      - cloudstore-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - user-order-service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cloudstore-frontend
    ports:
      - "80:80"
    networks:
      - cloudstore-network
    depends_on:
      - product-service
      - user-order-service

networks:
  cloudstore-network:
    driver: bridge