# =============================================
# APPLICATION
# =============================================
spring.application.name=user-order-service
server.port=8082

# =============================================
# H2 DATABASE (local development)
# =============================================
spring.datasource.url=jdbc:h2:mem:cloudstoredb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =============================================
# JPA / HIBERNATE
# =============================================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# =============================================
# H2 CONSOLE
# =============================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# =============================================
# LOGGING
# =============================================
logging.level.root=INFO
logging.level.com.cloudstore=DEBUG