# =============================================
# APPLICATION
# =============================================
spring.application.name=user-order-service
server.port=8082

# =============================================
# H2 DATABASE (local development)
# =============================================

# Use H2 in-memory database
spring.datasource.url=jdbc:h2:mem:cloudstoredb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =============================================
# JPA / HIBERNATE
# =============================================

# Automatically create tables from our Entity classes
# "create-drop" means: create tables when app starts, drop them when app stops
spring.jpa.hibernate.ddl-auto=create-drop

# Show SQL queries in the console (useful for learning/debugging)
spring.jpa.show-sql=true

# Format the SQL so it's readable
spring.jpa.properties.hibernate.format_sql=true

# Tell Hibernate we are using H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# =============================================
# H2 CONSOLE (web interface to see database)
# =============================================

# Enable the H2 console
spring.h2.console.enabled=true

# URL to access it: http://localhost:8082/h2-console
spring.h2.console.path=/h2-console

# =============================================
# LOGGING
# =============================================
logging.level.root=INFO
logging.level.com.cloudstore=DEBUG