# Application Name
spring.application.name=user-order-service

# Port - IMPORTANT: must be different from product-service (8081)
server.port=8082

# Logging
logging.level.root=INFO
logging.level.com.cloudstore=DEBUG