deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: [docker-push]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
    - name: Deploy user-order-service to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_USER_ORDER_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo docker pull musfikhilaly/cloudstore-user-order-service:latest
          sudo docker stop user-order-service || true
          sudo docker rm user-order-service || true
          sudo docker run -d --restart always --name user-order-service -p 8081:8082 \
            -e SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
            musfikhilaly/cloudstore-user-order-service:latest

    - name: Deploy product-service to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_PRODUCT_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo docker pull musfikhilaly/cloudstore-product-service:latest
          sudo docker stop product-service || true
          sudo docker rm product-service || true
          sudo docker run -d --restart always --name product-service -p 8080:8081 \
            musfikhilaly/cloudstore-product-service:latest